#include "fastfix/profile/builder_codegen.h"

#include <fstream>
#include <sstream>
#include <string>

namespace fastfix::profile {

namespace {

auto DefaultNamespaceName(const NormalizedDictionary& dictionary) -> std::string {
    return "fastfix::generated::profile_" + std::to_string(dictionary.profile_id);
}

}  // namespace

auto GenerateCppBuildersHeader(
    const NormalizedDictionary& dictionary,
    std::string_view namespace_name) -> base::Result<std::string> {
    const auto resolved_namespace = namespace_name.empty() ? DefaultNamespaceName(dictionary) : std::string(namespace_name);

    std::ostringstream out;
    out << "#pragma once\n\n";
    out << "#include <cstdint>\n\n";
    out << "// Generated by fastfix-dictgen.\n\n";
    out << "namespace " << resolved_namespace << " {\n\n";
    out << "inline constexpr std::uint64_t kProfileId = " << dictionary.profile_id << "ULL;\n";
    out << "inline constexpr std::uint64_t kSchemaHash = " << dictionary.schema_hash << "ULL;\n\n";
    out << "}  // namespace " << resolved_namespace << "\n";
    return out.str();
}

auto WriteCppBuildersHeader(
    const std::filesystem::path& path,
    const NormalizedDictionary& dictionary,
    std::string_view namespace_name) -> base::Status {
    auto header = GenerateCppBuildersHeader(dictionary, namespace_name);
    if (!header.ok()) {
        return header.status();
    }

    if (const auto parent = path.parent_path(); !parent.empty()) {
        std::error_code error;
        std::filesystem::create_directories(parent, error);
        if (error) {
            return base::Status::IoError("unable to create builder output directory: '" + parent.string() + "'");
        }
    }

    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (!out.is_open()) {
        return base::Status::IoError("unable to open generated builder header for writing: '" + path.string() + "'");
    }

    out.write(header.value().data(), static_cast<std::streamsize>(header.value().size()));
    if (!out.good()) {
        return base::Status::IoError("unable to write generated builder header: '" + path.string() + "'");
    }

    return base::Status::Ok();
}

}  // namespace fastfix::profile
